name: Build and Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  VERSION: '1.0.3'

jobs:
  build:
    name: Build TrollInstallerX
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          submodules: true

      - name: Pre theos
        run: |
         curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos > theos
         sed -i '' 's/get_sdks$//g' theos
         bash theos

      - name: Setup Environment
        run: echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Set env
        run: |
          sT=$(TZ=EST date +'%S')
          echo "msT=$(date -j -f "%Y-%m-%d %H:%M:%S" "$(TZ=EST date +'%Y-%m-%d %H:%M'):${sT}" +%s)" >> $GITHUB_ENV
          echo "logT=$(TZ=EST date +'%Y%m%d %H:%M'):${sT}" >> $GITHUB_ENV

      - name: Print env
        run: |
          echo ${{ env.VERSION }}
          echo ${{ env.msT }}
          echo ${{ env.logT }}

      - name: Pre body
        run: |
          echo -e "Update Time：${{ env.logT }}" >> release.txt
          echo -e "> - Synchronize official1.0.3Official version update，Simplified Chinese Chinese compilation." >> release.txt

      - name: Build ipa
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Release ipa
        uses: softprops/action-gh-release@v1
        with:
          name: TrollInstallerX_${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          target_commitish: main
          body_path: release.txt
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: |
           *.ipa
